version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: tour_agency_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tour_agency
      MYSQL_USER: tour_user
      MYSQL_PASSWORD: tour_pass
    ports:
      - "3306:3306"



volumes:
  db_data: